services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "26"
      CPU_CORES: "10"
      RAM_SIZE: "50G"
      WIDTH: "1680"
      HEIGHT: "1050"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - ./macos:/storage
    restart: always
    stop_grace_period: 60m
